### ISSUE TITLE
ROS Noetic Troubleshoot 

### ISSUE THREAD

**Issue by davidau8195** [UbiquityRobotics/raspicam_node#122]
HI, 

I am trying to install the packages for ROS Noetic in Ubuntu 20.04 for Raspicam Node. 

I read your readme file and it mentions that I need to add the repository before running apt install ros-kinetic-node. I go to the website: https://packages.ubiquityrobotics.com/

I try to run the sudo apt-key adv ... command and got an error message saying keyserver received failed: No name. 

Is there something that I am doing wrong?

**Comment by anfederman** [comment]
I don't understand. If you are running Noetic on a Raspberry Pi Ubuntu
20.04, Raspicam-node needs to be built in catkin. It should work on the
beta sd card image for ARM32, and I have built it on ARM64. You cannot
install it from Debs.

ALSO the old apt keys for Xenial expired, so we need to get those
regenerated. Apt upgrade is failing for Ubuntu 16.04. I am unclear what you
are attempting to do. Installing a kinetic version of Raspicam on a noetic
running RPi?

**Comment by davidau8195** [comment]
Thanks for the reply. Sorry, I am new to the ROS community. I manage to get the Raspicam-node packages from having built at the catkin. 

I am not sure if this should be a new thread or continue this one: 

I see that there is an existing issue with the following when building the Raspicam-node:

CMake Error at raspicam_node/CMakeLists.txt:30 (MESSAGE): Could not find mmal libraries

The only difference is that I am using ROS Noetic instead of ROS Melodic. 

Has there been a resolution to this issue before?

**Comment by anfederman** [comment]
I think this is an issue discussed on another thread in Ubiquity robotics
discourse. I will try to find the link to get the Raspicam node to compile
I am pretty sure it now can work on both Arm32 and ARM64 once the proper
libraries are installed. I am away from my computer, so I will give you the
recipe tomorrow.

**Comment by anfederman** [comment]
This is how I got raspicam_node working via catkin_make on ARM64.  This
should work for the ARM32 RPI as well,

though Idid get it working on ARM32 by a snap install of Rpi-userland and
copying the vclib files to /opt.  the key is making sure

raspistill is working before trying to install the raspicam node.


after a standard server install,  I did the following


added wifi, lubutu and assorted goodies

sudo apt install libraspberrypi-bin libraspberrypi-dev

  added  start_x=1, gpu_mem=128  to config.txt


full desktop and catkin install

git clone of raspicam_node

**Comment by JanezCim** [comment]
had the same error when compiling raspicam_node on Noetic: 
`CMake Error at raspicam_node/CMakeLists.txt:30 (MESSAGE): Could not find mmal libraries`
and rosdep could not solve this.

I solved it by simply installing
`sudo apt install libraspberrypi-dev libraspberrypi0`

@davidau8195 could you solve your problem like this?

**Comment by davidau8195** [comment]
@JanezCim 

I just follow his later instruction: 

I ran this before the source install the raspicam_node on Noetic:

`sudo apt install libraspberrypi-bin libraspberrypi-dev `

Also, I am currently using the ROS Noetic with Raspberry Pi 3B+. I didn't use the libraspberrypi0 but its bin instead.

**Comment by JanezCim** [comment]
okay, and did that solve it in the end for you? If yes, we can close this issue :)

**Comment by davidau8195** [comment]
Yes. It works now.
