### ISSUE TITLE
Will this create a point cloud?

### ISSUE THREAD

**Issue by domhel** [UbiquityRobotics/raspicam_node#124]
Hello,
I am very new to this ROS world so this is probably a stupid question.
I have one Raspberry Pi Cam V2 and I want to use [PX4-Obstacle Avoidance](https://github.com/PX4/PX4-Avoidance#camera) which requires a point cloud at `/point_cloud`.
But I've seen that you have to have either a stereo camera or lidar for that, so this won't work?

Have I answered my own question or is it possible somehow?

Thanks

**Comment by anfederman** [comment]
That is correct you need a stereo or depth camera like an Xtion for a point
cloud. A picam  can be used with calibrated markers for navigation. Both
lidar and 3d cameras are now more affordable.
