### ISSUE TITLE
We should do a release soon

### ISSUE THREAD

**Issue by jim-v** [UbiquityRobotics/raspicam_node#32]

**Comment by rohbotics** [comment]
Try the deb here. https://packages.ubiquityrobotics.com/ubuntu/ubiquity-testing/pool/main/r/ros-kinetic-raspicam-node/ros-kinetic-raspicam-node_0.2.2-0xenial_armhf.deb 

You can install it with `dpkg -i`.

If it is good, I will sync to the main repo.

**Comment by jim-v** [comment]
It looks good:  fiducials are detected when `roslaunch magni_nav aruco.launch` is run, and `roslaunch  raspicam_node camerav2_410x308_30fps.launch` works.

```$ apt-cache policy ros-kinetic-raspicam-node 
ros-kinetic-raspicam-node:
  Installed: 0.2.2-0xenial
  Candidate: 0.2.2-0xenial
  Version table:
 *** 0.2.2-0xenial 100
        100 /var/lib/dpkg/status
     0.2.1-0xenial 500
        500 https://packages.ubiquityrobotics.com/ubuntu/ubiquity xenial/main armhf Packages
```
