### ISSUE TITLE
Missing Launch File

### ISSUE THREAD

**Issue by anfederman** [UbiquityRobotics/raspicam_node#33]
magni_demos fiducial_follow.launch 
... logging to /home/ubuntu/.ros/log/04b680ea-ce4a-11e7-941f-b92814654e31/roslaunch-ubiquityrobotB5C4-4408.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

while processing /opt/ros/kinetic/share/raspicam_node/launch/camerav2_410x308_30fps.launch:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: u'/opt/ros/kinetic/share/raspicam_node/launch/camerav2_410x308_30fps.launch'
The traceback for the exception was written to the log file

**Comment by rohbotics** [comment]
Run `sudo apt update` and `sudo apt-upgrade` I just pushed the new release up.
