### ISSUE TITLE
camera_component not initialized

### ISSUE THREAD

**Issue by ll7** [UbiquityRobotics/raspicam_node#36]
If I type:  
```
roslaunch raspicam_node camerav1_1280x720.launch
```
I get the following error:
```
camera_component not initialzed
```
The camera is not working and I don't know how to fix this. Any help would be appreciated :-)

**Comment by ll7** [comment]
Sorry, forgot one installation step. Thanks for the package.

**Comment by ChunJyeBehBeh** [comment]
may I know is which step you forget ?

**Comment by JADGardner** [comment]
> may I know is which step you forget ?

In one terminal launch the raspicam_node
```console
roslaunch raspicam_node camera_module_v2_640x480_30fps.launch
```

and then in another terminal use:
```console
rosservice call /raspicam_node/start_capture
```
