### ISSUE TITLE
Raspicam_node generates blackened images where as uvc_camera doesn't produce blackened images .

### ISSUE THREAD

**Issue by chrissunny94** [UbiquityRobotics/raspicam_node#42]
I was trying to run the magni_nav , aurco.launch .
It calls the raspicam_node to publish the images , the node generates highly blackened images .

I tried all the different launch files in  raspicam_node . Same result always .(blackened images)

Also , Can I make the fiducial_slam work with uvc_camera node ? 
I tried publishing the topics in the correct name , but it didn't work. 

Ps:- I am using a 5mp raspi_cam .(probably a Chinese clone )

**Comment by amerkay** [comment]
Did you figure this out? I'm having the same trouble.

**Comment by chrissunny94** [comment]
Yes , you can adjust the ISO and other settings from RQT 


    rosrun rqt_reconfigure rqt_reconfigure

**Comment by amerkay** [comment]
I think the problem is my lens, not for low light. Thanks for the reply though.
