### ISSUE TITLE
Cmake error and cannot run raspi node lastest apt update

### ISSUE THREAD

**Issue by timlo94** [UbiquityRobotics/raspicam_node#44]

**Comment by timlo94** [comment]
![20180521_093910](https://user-images.githubusercontent.com/32585422/40286656-ef887638-5c97-11e8-9508-42d988f90e69.jpg)

**Comment by timlo94** [comment]
![20180521_094145](https://user-images.githubusercontent.com/32585422/40286689-294c70e0-5c98-11e8-8963-0df101acb7f8.jpg)

**Comment by rohbotics** [comment]
Somehow I must of missed this issue. Sorry for the very late response.

Is this still an issue?

Looks like you ran out of memory. You can try adding swap with `sudo apt install dphys-swapfile`
