### ISSUE TITLE
raspicam_node/image_raw

### ISSUE THREAD

**Issue by ChunJyeBehBeh** [UbiquityRobotics/raspicam_node#45]
Hello, 

Why my raspicam_node/image_raw topic don't have publisher?

--------------------------------------------------------------------
pi@pi-desktop:~$ rostopic info /raspicam_node/image_raw
Type: sensor_msgs/Image

Publishers: None

Subscribers: 
 * /image_view_1527236662447076777 (http://pi-desktop:35575/)

**Comment by amerkay** [comment]
Just run this node to republish uncompressed:
`rosrun image_transport republish compressed in:=/raspicam_node/image raw out:=/raspicam_node/image`
