### ISSUE TITLE
set video_device

### ISSUE THREAD

**Issue by Gil401** [UbiquityRobotics/raspicam_node#46]
Where can I change the video port (such as /dev/video0 /dev/video1)?
If is not possible, how can I use raspicam_node with USB cam?

thanks,
Gil

**Comment by rohbotics** [comment]
Raspicam_node is for the Raspberry Pi that plugs into the Camera Port of the Raspberry Pi only.

You are probably looking for something like http://wiki.ros.org/uvc_camera
