### ISSUE TITLE
camera config path issue?

### ISSUE THREAD

**Issue by wezzoid** [UbiquityRobotics/raspicam_node#53]
Even with one of the demo launch files, the node cannot find the config yaml. It seems as if it's ignoring the config line in the launch file and looking in ~/.ros/camera_info instead.

https://i.imgur.com/CVn7zCS.png

**Comment by rohbotics** [comment]
The node first loads calibration from the package, then loads from the home directory path.

This allows users to load custom calibration files, even they installed from debs.
