### ISSUE TITLE
Raw output errors

### ISSUE THREAD

**Issue by ijsmallman** [UbiquityRobotics/raspicam_node#56]
Decoding the CompressedImage stream is adding a prohibitive amount of latency to my application, so I'm trying to investigate using raw images instead.

I've seen in your code you can enable raw Image output on raspicam_node/image by adding `<param name="enable_raw" value="true"/>` to the launch file.

This seems to work, but rviz and my node(s) are struggling to process the topic. I get the following error from rviz for example:
```
[ERROR] [1539965934.276631376]: Error loading image: OGRE EXCEPTION(2:InvalidParametersException): Stream size does not match calculated image size in Image::loadRawData at /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreImage.cpp (line 283)
```
From the CV bridge I get:
```
mg = bridge.imgmsg_to_cv2(msg)
File "/opt/ros/kinetic/lib/python2.7/dist-packages/cv_bridge/core.py", line 171, in imgmsg_to_cv2
    dtype=dtype, buffer=img_msg.data)
TypeError: buffer is too small for requested array
```
Is this a bug or do I need to enable something else to work with raw images?

**Comment by rohbotics** [comment]
Are you running the latest code from source? (the kinetic branch)

Running a modified version of `roslaunch raspicam_node  camerav2_1280x960_10fps.launch` is working fine for me in both rqt_image_view and rviz

**Comment by ijsmallman** [comment]
I tried switching to the kinetic branch (and confirmed the RPi is indeed running kinetic). I also tried running a modified version of `camerav2_1280x960_10fps.launch` as you did and I am still getting those errors.

The only other detail I can think that might be relevant is that (in addition to processing the images onboard) I am viewing the image stream on my laptop connected via wifi. I have setup ROS_IP and ROS_MASTER_URI on both ends so that messages are transmit over the network.

**Comment by rohbotics** [comment]
Ok, my tests were also with a laptop connected over WiFi.

Does `rostopic echo` of the image topic return data on the laptop?

Also make sure you are running ROS Kinetic on your laptop as well, and have up-to-date packages on both the Pi and the Laptop.

**Comment by rohbotics** [comment]
Closing due to age, feel free to reopen if you are still facing the issue
