### ISSUE TITLE
Use full resolution of cam v2

### ISSUE THREAD

**Issue by julled** [UbiquityRobotics/raspicam_node#72]
Hi i try to use the pi cam v2 with full resolution (3280x2464) but there is an issue when starting in that mode. Is this a known issue? And can i fix this somehow?
![Selection_164](https://user-images.githubusercontent.com/8696195/54999312-3f948280-4fd0-11e9-84db-4e729714a3c1.png)

**Comment by julled** [comment]
fixed by increasing gpu memory via memory split in raspi-config.

**Comment by maxammann** [comment]
Increasing it to 220MB seems to work!

**Comment by machinekoder** [comment]
Maybe also useful: https://www.raspberrypi.org/forums/viewtopic.php?t=197585

Did you also see a `could not convert from bgr8 to rgb8` error when using higher resolutions?

**Comment by maxammann** [comment]
I don't think so. It just failed to init.
