### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by Medicus3453** [UbiquityRobotics/raspicam_node#81]
Hey,

is it possible to choose the spot, where to save those taken pictures?
and is ist possible to take time lapse?

BR

**Comment by rohbotics** [comment]
I am not sure what you are asking for.

This is a ROS node that publishes the captured images through ROS, it doesn't save any images anywhere.

There is no built in timelapse support, but you could write a script that captures an image every X time and then compile that into a video.
