### ISSUE TITLE
Build stuck on raspicam_node_generate_messages

### ISSUE THREAD

**Issue by Le0nLyn** [UbiquityRobotics/raspicam_node#87]
Hi,
I am trying to build from source on my raspberry pi 3 B, but the build process stucks on **Building CXX object raspicam_node/CMakeFiles/raspicam_node.dir/src/RaspiCamControl.cpp.o**.
I'm also using the latest Ubiquity Image from https://downloads.ubiquityrobotics.com

**Comment by rohbotics** [comment]
Hi,

You may want to try compiling with fewer cores due to memory limitations on the Pi, `catkin_make -j1`.

**Comment by Le0nLyn** [comment]
Hi,
I ended up using the pre-built binary, but using the `-j1` flag did resolve the issue. Thank you!
