### ISSUE TITLE
wrong format for compressed image

### ISSUE THREAD

**Issue by MoffKalast** [UbiquityRobotics/raspicam_node#96]
The message CompressedImage is specified with the following format enum:

```
string format        # Specifies the format of the data
                     #   Acceptable values:
                     #     jpeg, png
```
The node publishes with the format set to "jpg" which breaks compatibility with other nodes that rely on the acceptable values.

**Comment by rohbotics** [comment]
Hey @MoffKalast Looks like this was already fixed in https://github.com/UbiquityRobotics/raspicam_node/pull/79 for the exact same issue 

Looks like we need to run a new release of raspicam_node
