### ISSUE TITLE
Camera configuration file (yaml) not found.

### ISSUE THREAD

**Issue by elpidiovaldez** [UbiquityRobotics/raspicam_node#97]
I find that the camera launch files result in an error message like:
`[ INFO] [1586890062.630439472]: Unable to open camera calibration file [/home/paul/.ros/camera_info/camerav2_410x308.yaml]
[ WARN] [1586890062.630601378]: Camera calibration file /home/paul/.ros/camera_info/camerav2_410x308.yaml not found.
`
The system seems to be looking for camera_info in the wrong place. The launch file specifies the location as:
`<param name="camera_info_url" value="package://raspicam_node/camera_info/camerav2_410x308.yaml"/>`

which seems like it should resolve to the camera_info directory in the raspicam_node package.

I can easily fix the problem by copying the camera_info directory into ~/.ros but I think that raspicam is failing to pick up the location specified in the launch file.

**Comment by rohbotics** [comment]
Hi @elpidiovaldez 

Raspicam looks .ros first, and then goes to the specified default calibration file. This is to allow people to calibrate their intrinsics without writing into the raspicam package, which may require root permissions. 

If you look further down the log you should see `Camera successfully calibrated from default file`
